In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

arr = np.array(my_list)

In [10]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

# Instantiating a basic Array

In [34]:
my_matrix = np.array(my_matrix)

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Instatiating a zero Array

In [16]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

# This is to instating an EVEN spaced matrix, of 10 rows

In [15]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [19]:
arr = np.arange(25)

In [22]:
ranarr = np.random.randint(0,50,10)

# RESHAPING is useful, you are changing the dimensions of a n x m list or array into a new array

In [26]:
arr = arr.reshape(5,5)

In [30]:
arr.shape

(5, 5)

In [31]:
# Note here, the index is the MATRIX ROW in some caseas

In [37]:
my_matrix[0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
my_matrix[0][2]
#is the same as
my_matrix[0,2]

3

# This is important - to get the specifics on a certain allocation

In [38]:
my_matrix[:2,2:]

array([[3],
       [6]])

# Conditional Selection is REALLY Important

In [41]:
c_array = np.arange(1,11)

In [42]:
c_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
c_array > 5

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [44]:
# This allows you to get positions where something is TRUE!
c_array[c_array > 5]

array([ 6,  7,  8,  9, 10])

# Numpy OPERATIONS

In [46]:
np.max(c_array)

10